version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - microservices-net

  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
